In [1]:
import numpy as np

In [2]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[117, 711, 171], [711, 171, 117]])
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [6]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:, 0]

array([117, 711])

In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1]

array([711, 171, 117])

In [8]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [11]:
X_pt = torch.tensor([[117, 711, 171], [711, 171, 117]])
X_pt

tensor([[117, 711, 171],
        [711, 171, 117]])

In [12]:
X_pt.shape

torch.Size([2, 3])

In [13]:
X_pt[:, 0]

tensor([117, 711])

In [14]:
X_pt[1]

tensor([711, 171, 117])

In [1]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [2]:
X_tf = tf.Variable([[117, 711, 171], [711, 171, 117]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[117, 711, 171],
       [711, 171, 117]], dtype=int32)>

In [4]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [7]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([117, 711], dtype=int32)>

In [9]:
X_tf[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([711, 171, 117], dtype=int32)>