In [3]:
import numpy as np

In [4]:
# buat vector x dengan ukuran 3x1
x = np.array([[117], [171], [711]])
x

array([[117],
       [171],
       [711]])

In [5]:
# hitung nilai L2 norm dari vector x
x_l2 = np.linalg.norm(x)
x_l2

np.float64(740.5747767781455)

In [7]:
# buat vector v dengan elemen (3,4)
v = np.array([3, 4])
v

array([3, 4])

In [8]:
# hitung nilai L2 norm dari vector v
v_l2 = np.linalg.norm(v)
v_l2

np.float64(5.0)

In [11]:
# tampilkan unit vector dari vector v
v_unit = v_l2 / v
v_unit

array([1.66666667, 1.25      ])

In [10]:
# hitung panjang unit vector dari vector v
v_unit_l2 = np.linalg.norm(v_unit)
v_unit_l2

np.float64(2.0833333333333335)