In [2]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
x = np.array([[117], [171], [711]])
x

array([[117],
       [171],
       [711]])

In [ ]:
# hitung panjang vector x
panjang = np.linalg.norm(x)
panjang

np.float64(740.5747767781455)

In [ ]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [ ]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [ ]:
# akses elemen pertama dari vector x
x[0, 0]

np.int64(117)

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0, 0])

numpy.int64

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[117, 171, 711]])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [3]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[117], [171], [711]])
y_t = y.T
y_t

array([[117, 171, 711]])

In [4]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t (Pytorch)
x_pt = torch.tensor([[117], [171], [711]])
x_pt_t = x_pt.T
x_pt_t

tensor([[117, 171, 711]])

In [ ]:
# tampilkan ukuran dari vector x_t (PyTorch)
x_pt_t.shape

torch.Size([1, 3])

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t (Tensorflow)
x_tf = tf.Variable([[117], [171], [711]])
tf.transpose(x_tf)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[117, 171, 711]], dtype=int32)>

In [ ]:
# tampilkan ukuran dari vector x_t (Tensorflow)
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>